version: "3.9"

services:
  database:
    image: "postgres"
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    volumes:
      - ${PWD}/volumes/database-data:/var/lib/postgresql/data/

  session-cache:
    image: "redis:alpine"
    restart: always
    command: redis-server --requirepass ${SESSION_DB_PASSWORD} --port ${SESSION_DB_PORT}
    ports:
      - "${SESSION_DB_PORT}:${SESSION_DB_PORT}"
    environment:
      SESSION_DB_PASSWORD: ${SESSION_DB_PASSWORD}
      SESSION_DB_PORT: ${SESSION_DB_PORT}
    volumes:
      - ${PWD}/volumes/session-cache-data:/bitnami/redis/data
